name: Artifacts, environment and secrets (build and deploy)
on: [push, workflow_dispatch]
env: # тут ми задаємо глобальні зміні середовища
  GB_SECRET: ${{ secrets.GB_SECRET }}
  NOT_SECRET: 42
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print env var
        run: |
          echo "${{ env.NOT_SECRET }}"
          echo "${{ env.GB_SECRET }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # створюємо artifact
        with:
          name: build-files # назва артифакту
          path: dist # бере теку dist (для майбутнього артифакту), яка створюється після команди build
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    env: # тут ми задаємо локальні зміні середовища
#      NODE_ENV: production # зміна із значенням production поламає workflow,
#                          # якщо задати її глобально на найвищому рівні тому, що
#                          # "production" не запускає інсталяцію devDependencies
#    steps:
#      - name: Print env vars
#        run: echo "${{ env.NODE_ENV }}"
#      - name: Get build project (Download artifact)
#        uses: actions/download-artifact@v5 # додаємо можливість побачити та завантажити наш артифакт
#        with:
#          name: build-files # назва артифакту, з яким необхідно працювати
  deploy-vercel:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build project (Download artifact)
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist # Завантажуємо артефакт в теку dist
      - name: 'Debug: Display partial IDs'
        run: |
          ORG_ID_VAL="${{ secrets.VERCEL_ORG_ID }}"
          PRJ_ID_VAL="${{ secrets.VERCEL_PROJECT_ID }}"
          echo "VERCEL_ORG_ID starts with: '${ORG_ID_VAL:0:5}' and ends with: '${ORG_ID_VAL: -5}'"
          echo "VERCEL_PROJECT_ID starts with: '${PRJ_ID_VAL:0:5}' and ends with: '${PRJ_ID_VAL: -5}'"
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25 # Використовуємо екшен для деплою
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' # Додаємо прапорець для деплою в production
