name: Artifacts, environment and secrets (build and deploy)
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project (Download artifact)
        uses: actions/download-artifact@v5
        with:
          name: build-files
