name: Test React App
on: push # Реагує на зміни, які ми заливаємо у репозиторій
jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get access to the repository code
        uses: actions/checkout@v4 # на пряму github немає доступу до нашого репозиторію. Тому ми використовуємо стороній action
      - name: Install deps
        run: npm ci
      - name: Test app
        run: npm run test